URL = "https://archives.nseindia.com/content/historical/EQUITIES/"
FIVE_DAYS_PATH = "DATA/5 DAYS"
TEN_DAYS_PATH = "DATA/10 DAYS"
TWENTY_DAYS_PATH = "DATA/20 DAYS"
FIFTY_DAYS_PATH = "DATA/50 DAYS"
DIRECTORIES = [FIVE_DAYS_PATH, TEN_DAYS_PATH, TWENTY_DAYS_PATH, FIFTY_DAYS_PATH]
TWO_HUNDRED_DAYS_PATH = "DATA/200 DAYS"
DATE_FORMAT = '%Y-%m-%d'

FIVE_SMA = "SMA-5DAYS.xlsx"
TEN_SMA = "SMA-10DAYS.xlsx"
TWENTY_SMA = "SMA-20DAYS.xlsx"
FIFTY_SMA = "SMA-50DAYS.xlsx"
RESULTS_FILE = "Results.xlsx"